version: 2.1

jobs: 
  build:
    docker:
      - image: circleci/11.14.0
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: tests
          command: npm test      